Vagrant.configure("2") do |config|
  config.vm.define "v", primary: true do |v|
    v.vm.box = "bento/ubuntu-20.04"
    v.vm.hostname = 'Elk-Demo-183'
    v.vm.network :private_network, ip: "192.168.56.183"    
	
	v.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--name", "Elk-Demo-183"]
	  v.customize ["modifyvm", :id, "--memory", 2048]
	  v.customize ["modifyvm", :id, "--cpus", 2]
    end	 
 end
end
