FROM ubuntu
RUN apt-get update
RUN ["apt-get" , "install" , "figlet"]
CMD ["figlet", "-f", "script", "hello"]
# ENTRYPOINT ["figlet", "-f", "script"]


# ENTRYPOINT ["figlet1", "-f", "script"]

# CMD ["hello"]



# CMD ["figlet", "-f", "script", "hello"]

